config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get '/users/:id/password/edit', to: 'users#password_edit', as: 'password'
  patch '/users/:id/password/edit', to: 'users#password_update', as: 'update_password'
  
  resources :posts do
    resources :comments, only: [:create, :edit, :destroy, :update]
  end
  
  resources :users
  
  resource :session, only: [:new, :create, :destroy]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index
    end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-default navbar-dark">
<a class="navbar-brand" href="<%= root_path %>">Blog On Rails</a>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
  aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse" id="navbarNav">
  <ul class="navbar-nav ml-auto mt-lg-0">
    <li class="nav-item">
      <a class="nav-link" href="<%= root_path %>">Home</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="<%= posts_path %>">Posts</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="<%= new_post_path %>">New Post</a>
    </li>
    <% if user_signed_in? %>
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="<%= root_path %>" id="navbarDropdown" role="button"
        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <%= current_user.full_name %>
      </a>
      <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <%= link_to "My Profile", edit_user_path(current_user), class:"dropdown-item", style:"color:blue" %>
        <div class="dropdown-divider"></div>
        <%= link_to "Sign Out", session_path, method: :delete, data: {confirm: "Are you sure you want to Sign Out?"}, class:"dropdown-item", style:"color:blue"%>
      </div>
    </li>
    <% else %>
    <li class="nav-item">
      <a class="nav-link" href="<%= new_session_path %>">Sign In</a>
    </li>
    <% end %>
</div>
</ul>
</div>
</nav>
<%= flash[:notice]%>

app/views/welcome/index.html.erb
<%= render 'navigation' %>
<div class="fullwidth">
</div>