config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get '/users/:id/password/edit', to: 'users#password_edit', as: 'password'
  patch '/users/:id/password/edit', to: 'users#password_update', as: 'update_password'
  
  resources :posts do
    resources :comments, only: [:create, :edit, :destroy, :update]
  end
  
  resources :users
  
  resource :session, only: [:new, :create, :destroy]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many(:comments, dependent: :destroy)

    validates :title, presence: true
    validates :body, presence: true
    validates :view_count, numericality: {greater_than_or_equal_to: 0}
    
    before_validation :capitalize_title 
    before_validation :default_view_count

    private
    def capitalize_title
        self.title.capitalize!
    end

    def default_view_count
        self.view_count ||= 0
      end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    before_action :find_post, only: [:edit,:update,:show, :destroy]
    before_action :authorize!, only: [:edit, :update,]

    def new
        @post = Post.new
    end

    def create
        @post = Post.new post_params
        @post.user = current_user
        if @post.save
            flash[:notice] = 'Post Created Successfully'
            redirect_to post_path(@post.id)
        else
            render :new
        end
    end

    def edit
    end

    def update
        if @post.update post_params
            flash[:notice] = 'Post updated Successfully'
            redirect_to post_path(@post.id)
        else
            render :edit
        end
    end

    def index 
        @posts= Post.order(created_at: :desc)
    end

    def show
        @new_comment = Comment.new
        @comments = @post.comments.order(created_at: :desc)
        @post.update_columns(view_count: @post.view_count + 1)
    end

    def destroy
        @post.destroy
        redirect_to posts_path
    end

    private
    def find_post
        @post=Post.find_by id:params[:id]
        if @post == nil
            redirect_to root_path, notice: "Post Does Not Exist"
        end
    end

    def post_params
        params.require(:post).permit(:title, :body)
    end

    def authorize! 
        unless can?(:crud, @post)
            redirect_to root_path, notice: 'Not Authorized. Access Denied' 
        end
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-default navbar-dark">
<a class="navbar-brand" href="<%= root_path %>">Blog On Rails</a>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
  aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse" id="navbarNav">
  <ul class="navbar-nav ml-auto mt-lg-0">
    <li class="nav-item">
      <a class="nav-link" href="<%= root_path %>">Home</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="<%= posts_path %>">Posts</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="<%= new_post_path %>">New Post</a>
    </li>
    <% if user_signed_in? %>
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="<%= root_path %>" id="navbarDropdown" role="button"
        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <%= current_user.full_name %>
      </a>
      <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <%= link_to "My Profile", edit_user_path(current_user), class:"dropdown-item", style:"color:blue" %>
        <div class="dropdown-divider"></div>
        <%= link_to "Sign Out", session_path, method: :delete, data: {confirm: "Are you sure you want to Sign Out?"}, class:"dropdown-item", style:"color:blue"%>
      </div>
    </li>
    <% else %>
    <li class="nav-item">
      <a class="nav-link" href="<%= new_session_path %>">Sign In</a>
    </li>
    <% end %>
</div>
</ul>
</div>
</nav>
<%= flash[:notice] || flash[:alert]%>

app/views/posts/edit.html.erb
<%= render 'navigation' %>
<br>
<div class="sign-in-form container">
  <div class="sign-in-brand"><a href="<%= root_path %>" class="logo">Blog On Rails</a></div><br>
  <%= form_with model: @post, local: true do |f|%>
  <% if @post.errors.present?%>
  <p>
    <%= @post.errors.full_messages.join(', ') %>
  </p>
  <% end %>
  <div class="sign-in-content">
    <h3><strong>Edit Post</strong></h3>
    <strong><%= f.label :title, "Title"%></strong><br>
    <%= f.text_field :title, style:"width:100%;"%><br><br>
    <strong><%= f.label :body, "Body", cols:50, rows:3%></strong><br>
    <%= f.text_area :body, style:"width:100%;"%><br><br>
    <div>
      <%= f.submit "Edit Your Post", style:"width:100%;", class:"sign-in-button"%><br>
      <p class="terms-of-use"><br>
        By creating a Post, you agree to Blog on Rails's<br>
        <strong style="color:#0000EE;">Conditions of Use</strong> and <strong style="color:#0000EE;">Privacy
        Notice</strong>.</p>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<%= render 'navigation'%>
<br>
<div class="container">
    <div class="row">
        <% @posts.each do |post| %>
        <div class="col-lg-4 py-2">
            <div class="post-card">
                <h2><%=link_to( post.title.truncate(30, separator: " "), post_path(post.id)) %></h2>
                <div><%= post.body.truncate(50, separator: " ") %></div>
                <div class="post-card-footer"><small>views : <%=post.view_count%> | comment : <%= post.comments.count %> | Posted <%= remove_unwanted_words time_ago_in_words(post.created_at) %> ago </small></div>
            </div>
        </div>
        <% end %>
    </div>
</div>
</div>

app/views/posts/new.html.erb
<%= render 'navigation'%>
<br>
<div class="sign-in-form container">
  <div class="sign-in-brand"><a href="<%= root_path %>" class="logo">Blog On Rails</a></div><br>
  <%= form_with model: @post, local: true do |f|%>
    <div class="sign-in-content">
    <h3><strong>Create Post</strong></h3>
    <% if @post.errors.present?%>
    <p style="color:red;">
      <%= @post.errors.full_messages.join(', ') %>
    </p>
    <% end %>
    <strong><%= f.label :title, "Title"%></strong>
    <%= f.text_field :title, style:"width:100%;"%><br>
    <strong><%= f.label :body, "Body", cols:50, rows:3%></strong>
    <%= f.text_area :body, style:"width:100%;"%><br>
    <div>
      <%= f.submit "Create Your Post", style:"width:100%;", class:"sign-in-button"%><br>
      <p class="terms-of-use"><br>
        By creating a Post, you agree to Blog on Rails's<br>
        <strong style="color:#0000EE;">Conditions of Use</strong> and <strong style="color:#0000EE;">Privacy
        Notice</strong>.</p>
        
      <% end %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<%= render 'navigation' %>

<div class="show-post-container">
  <br>
  <small class="path">Home > Posts > <%= @post.title %></small>
  <div class="show-post p-3">
    <%= image_tag "wood3.jpg", alt: "post image", class:"post-image", style:"width:40%; height:auto;"%>
    <div class="post-header">
      <div class"post-flex">
        <h1 class="post-header1"><%= @post.title %></h1>
        <small style="color:black;">by <strong
            style="color:#0000EE;"><%= @post.user&.full_name || 'DELETED' %></strong></small><br>
        <small style="color:black;">Posted on
          <strong style="color:#0000EE;"><%= @post.created_at.strftime("%b %d, %Y") %> |
            <%= @comments.count %>
            comments</strong></small>
        <% if can? :crud, @post %>
        <div class="post-buttons">
          <%= link_to 'Edit Post', edit_post_path(@post.id), class: "edit-button"%>
          <%= link_to("Delete Post", post_path(@post), method: :delete, data:{confirm:'Are you sure?'}, class: "delete-button") %>
        </div>
        <% end %>
      </div>
      <p class="post-body"><%= @post.body %></p>
    </div>
  </div>
  <hr class="post-hr">
  <section>
    <%= form_with(model: [@post, @new_comment], local: true) do |f| %>
    <h4 class="comment-header"><strong>Comment this post</strong></h4>
    <% if @new_comment.errors.present? %>
    <p class="form-errors">
      <%= @new_comment.errors.full_messages.join(", ") %>
    </p>
    <% end %>
    <div class="form-group">
      <%= f.text_area(
            :body,
            cols: 50,
            rows: 3,
            placeholder:"What are your thoughts?",
            class: "form-control"
        ) %>
    </div>

    <%= f.submit 'Write a user comment', class: "comment-button"%>
    <% end %>

    <hr class="board">
    <div class="comment">
      <% @comments.each do |comment| %>
      <div class="comment-head">
        <%= image_tag "unknown", alt: "unknown user", class:"unknown-image", style:"width:3%; height:auto;"%>
        <div class="image-user">
          <strong>&nbsp;&nbsp;<%= comment.user&.full_name || 'DELETED' %> </strong>
        </div>
      </div>
      <small>Commented in <%= comment.created_at.strftime("%b %d, %Y") %></small>
      <div class="comment-body">
        <%= comment.body %> <br>
      </div>
      <small>
        <% if can?(:crud, comment) || can?(:crud, comment.post) %>
        <%= link_to(
                    "Delete",
                    post_comment_path(@post, comment),
                    method: :delete,
                    data: {
                        confirm: "Are you sure?"
                    }
                ) %>
        <% end %>
      </small>
      <% end %>
    </div>
  </section>
  <br>